using DS4Windows;
using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;

namespace DS4WindowsTests
{
    [TestClass]
    public class ViiperAuthenticatedStreamTests
    {
        private const string GoVectorPassword = "Ds4WGoVector2026";
        private const string GoPasswordKey =
            "120eb5e837779ba78c47fa0fe9a5591a13812af6570252c2dab36a353daab210";
        private const string GoAuthenticationTag =
            "4fbe205fe7d3ae403e26577a41b43b505330a496f9a698b6196a57dd81fe57ef";
        private const string GoSessionKey =
            "a0693dc0f7979b2b6b7676e3615706b968ad04dbb6aad8f77b5a84d7921e95dc";
        private const string GoClientRecordZero =
            "00000020000000000000000000000000d4a5432c838aa6a038940289cafd32605ffbce46";
        private const string GoServerRecordZero =
            "0000002f00000001000000000000000066092a7b649a10f88a99fc8c1e87b4b9fcdbe9a76ea5b8bc9b1d3790b73b9127b401c0";

        [TestMethod]
        public void FrozenGoSourceVectorsMatchHandshakeAndBothRecordDomains()
        {
            // Generated by VIIPER internal/server/api/auth at source revision
            // 7270672f92e3ce935452490e35554bd21b1cd141.
            byte[] clientNonce = Enumerable.Range(0, 32)
                .Select(value => (byte)value).ToArray();
            byte[] serverNonce = Enumerable.Range(32, 32)
                .Select(value => (byte)value).ToArray();
            byte[] passwordKey = ViiperAuthProtocol.DerivePasswordKey(
                GoVectorPassword);
            CollectionAssert.AreEqual(Convert.FromHexString(GoPasswordKey),
                passwordKey);
            byte[] sessionKey = ViiperAuthProtocol.DeriveSessionKey(
                passwordKey, serverNonce, clientNonce);
            CollectionAssert.AreEqual(Convert.FromHexString(GoSessionKey),
                sessionKey);

            byte[] response = Combine(Encoding.ASCII.GetBytes("OK\0"),
                serverNonce, Convert.FromHexString(GoServerRecordZero));
            var transport = new ScriptedDuplexStream(response, readChunk: 1);
            using Stream stream = ViiperAuthProtocol.AuthenticateClient(
                transport, GoVectorPassword, clientNonce);

            byte[] expectedHandshake = Combine(
                Encoding.UTF8.GetBytes(ViiperAuthProtocol.HandshakeMagic),
                clientNonce, Convert.FromHexString(GoAuthenticationTag));
            CollectionAssert.AreEqual(expectedHandshake,
                transport.Written.Take(expectedHandshake.Length).ToArray());

            byte[] ping = Encoding.ASCII.GetBytes("ping");
            stream.Write(ping, 0, ping.Length);
            CollectionAssert.AreEqual(Convert.FromHexString(
                    GoClientRecordZero),
                transport.Written.Skip(expectedHandshake.Length).ToArray());

            byte[] received = new byte[64];
            int length = stream.Read(received, 0, received.Length);
            Assert.AreEqual("{\"server\":\"VIIPER\"}",
                Encoding.ASCII.GetString(received, 0, length));
        }

        [TestMethod]
        public void EmptyRecordIsNotMisreportedAsEndOfStream()
        {
            byte[] key = Convert.FromHexString(GoSessionKey);
            byte[] wire = Combine(BuildRecord(key, 1, 0, Array.Empty<byte>()),
                BuildRecord(key, 1, 1, Encoding.ASCII.GetBytes("next")));
            using var encrypted = new ViiperEncryptedStream(
                new ScriptedDuplexStream(wire, readChunk: 1), key);
            byte[] result = new byte[4];
            Assert.AreEqual(4, encrypted.Read(result, 0, result.Length));
            Assert.AreEqual("next", Encoding.ASCII.GetString(result));
        }

        [DataTestMethod]
        [DataRow(2u, 0ul, "unknown direction")]
        [DataRow(1u, 1ul, "out of order")]
        [DataRow(0u, 0ul, "client direction")]
        public void InvalidReceiveNonceFailsClosedAndLatches(uint prefix,
            ulong counter, string scenario)
        {
            byte[] key = Convert.FromHexString(GoSessionKey);
            byte[] wire = BuildRecord(key, prefix, counter,
                Encoding.ASCII.GetBytes(scenario));
            using var encrypted = new ViiperEncryptedStream(
                new ScriptedDuplexStream(wire), key);
            byte[] output = new byte[128];
            Assert.ThrowsException<IOException>(() =>
                encrypted.Read(output, 0, output.Length));
            Assert.ThrowsException<IOException>(() =>
                encrypted.Read(output, 0, output.Length));
        }

        [TestMethod]
        public void ReplayAfterValidRecordFailsClosed()
        {
            byte[] key = Convert.FromHexString(GoSessionKey);
            byte[] wire = Combine(
                BuildRecord(key, 1, 0, new byte[] { 1 }),
                BuildRecord(key, 1, 0, new byte[] { 2 }));
            using var encrypted = new ViiperEncryptedStream(
                new ScriptedDuplexStream(wire), key);
            byte[] output = new byte[1];
            Assert.AreEqual(1, encrypted.Read(output, 0, 1));
            Assert.AreEqual((byte)1, output[0]);
            Assert.ThrowsException<IOException>(() =>
                encrypted.Read(output, 0, 1));
        }

        [TestMethod]
        public void TruncationCannotBecomeANewRecordOnRetry()
        {
            byte[] key = Convert.FromHexString(GoSessionKey);
            byte[] complete = BuildRecord(key, 1, 0,
                Encoding.ASCII.GetBytes("truncated"));
            byte[] truncated = complete.Take(complete.Length - 3).ToArray();
            using var encrypted = new ViiperEncryptedStream(
                new ScriptedDuplexStream(truncated, readChunk: 2), key);
            byte[] output = new byte[32];
            Assert.ThrowsException<EndOfStreamException>(() =>
                encrypted.Read(output, 0, output.Length));
            Assert.ThrowsException<EndOfStreamException>(() =>
                encrypted.Read(output, 0, output.Length));
        }

        [DataTestMethod]
        [DataRow(27u)]
        [DataRow(2097153u)]
        public void InvalidRecordLengthFailsClosed(uint encodedLength)
        {
            byte[] header = new byte[4];
            BinaryPrimitives.WriteUInt32BigEndian(header, encodedLength);
            using var encrypted = new ViiperEncryptedStream(
                new ScriptedDuplexStream(header),
                Convert.FromHexString(GoSessionKey));
            Assert.ThrowsException<IOException>(() =>
                encrypted.Read(new byte[1], 0, 1));
        }

        [TestMethod]
        public void ConcurrentWritesAreSerializedWithUniqueMonotonicNonces()
        {
            byte[] key = Convert.FromHexString(GoSessionKey);
            var transport = new ScriptedDuplexStream(Array.Empty<byte>());
            using var encrypted = new ViiperEncryptedStream(transport, key);
            Parallel.For(0, 64, value =>
            {
                byte[] payload = BitConverter.GetBytes(value);
                encrypted.Write(payload, 0, payload.Length);
            });

            byte[] wire = transport.Written;
            int offset = 0;
            var values = new HashSet<int>();
            for (ulong counter = 0; counter < 64; counter++)
            {
                uint length = BinaryPrimitives.ReadUInt32BigEndian(
                    wire.AsSpan(offset, 4));
                Assert.AreEqual(32u, length);
                ReadOnlySpan<byte> record = wire.AsSpan(offset + 4,
                    checked((int)length));
                Assert.AreEqual(0u,
                    BinaryPrimitives.ReadUInt32BigEndian(record));
                Assert.AreEqual(counter,
                    BinaryPrimitives.ReadUInt64BigEndian(record.Slice(4)));
                byte[] plaintext = DecryptRecord(key, record);
                Assert.IsTrue(values.Add(BitConverter.ToInt32(plaintext)));
                offset += 4 + checked((int)length);
            }
            Assert.AreEqual(wire.Length, offset);
            Assert.AreEqual(64, values.Count);
        }

        [TestMethod]
        public void MaximumInclusiveRecordAndSenderExhaustionAreEnforced()
        {
            byte[] key = Convert.FromHexString(GoSessionKey);
            var transport = new ScriptedDuplexStream(Array.Empty<byte>());
            using var encrypted = new ViiperEncryptedStream(transport, key,
                ulong.MaxValue, 0);
            byte[] maximum = new byte[
                ViiperEncryptedStream.MaximumPlaintextSize];
            encrypted.Write(maximum, 0, maximum.Length);
            Assert.AreEqual(4 + ViiperEncryptedStream.MaximumRecordSize,
                transport.Written.Length);
            Assert.ThrowsException<IOException>(() =>
                encrypted.Write(new byte[1], 0, 1));

            using var ordinary = new ViiperEncryptedStream(
                new ScriptedDuplexStream(Array.Empty<byte>()), key);
            Assert.ThrowsException<IOException>(() => ordinary.Write(
                new byte[ViiperEncryptedStream.MaximumPlaintextSize + 1],
                0, ViiperEncryptedStream.MaximumPlaintextSize + 1));
        }

        [TestMethod]
        public void AuthenticationRejectionUsesDedicatedFailureType()
        {
            var transport = new ScriptedDuplexStream(
                Encoding.UTF8.GetBytes("NO\0invalid password\n"));
            Assert.ThrowsException<ViiperAuthenticationException>(() =>
                ViiperAuthProtocol.AuthenticateClient(transport,
                    GoVectorPassword, new byte[32]));
        }

        private static byte[] BuildRecord(byte[] key, uint prefix,
            ulong counter, byte[] plaintext)
        {
            byte[] nonce = new byte[12];
            BinaryPrimitives.WriteUInt32BigEndian(nonce, prefix);
            BinaryPrimitives.WriteUInt64BigEndian(nonce.AsSpan(4), counter);
            byte[] ciphertext = new byte[plaintext.Length];
            byte[] tag = new byte[16];
            using (var cipher = new ChaCha20Poly1305(key))
            {
                cipher.Encrypt(nonce, plaintext, ciphertext, tag);
            }
            byte[] wire = new byte[4 + nonce.Length + ciphertext.Length +
                tag.Length];
            BinaryPrimitives.WriteUInt32BigEndian(wire,
                (uint)(wire.Length - 4));
            Buffer.BlockCopy(nonce, 0, wire, 4, nonce.Length);
            Buffer.BlockCopy(ciphertext, 0, wire, 16, ciphertext.Length);
            Buffer.BlockCopy(tag, 0, wire, 16 + ciphertext.Length,
                tag.Length);
            return wire;
        }

        private static byte[] DecryptRecord(byte[] key,
            ReadOnlySpan<byte> record)
        {
            ReadOnlySpan<byte> nonce = record.Slice(0, 12);
            ReadOnlySpan<byte> ciphertext = record.Slice(12,
                record.Length - 28);
            ReadOnlySpan<byte> tag = record.Slice(record.Length - 16);
            byte[] plaintext = new byte[ciphertext.Length];
            using var cipher = new ChaCha20Poly1305(key);
            cipher.Decrypt(nonce, ciphertext, tag, plaintext);
            return plaintext;
        }

        private static byte[] Combine(params byte[][] pieces)
        {
            byte[] result = new byte[pieces.Sum(piece => piece.Length)];
            int offset = 0;
            foreach (byte[] piece in pieces)
            {
                Buffer.BlockCopy(piece, 0, result, offset, piece.Length);
                offset += piece.Length;
            }
            return result;
        }

        private sealed class ScriptedDuplexStream : Stream
        {
            private readonly byte[] input;
            private readonly int readChunk;
            private readonly MemoryStream written = new MemoryStream();
            private int inputOffset;
            private bool disposed;

            internal ScriptedDuplexStream(byte[] input,
                int readChunk = int.MaxValue)
            {
                this.input = input ?? throw new ArgumentNullException(
                    nameof(input));
                this.readChunk = readChunk;
            }

            internal byte[] Written => written.ToArray();
            public override bool CanRead => !disposed;
            public override bool CanSeek => false;
            public override bool CanWrite => !disposed;
            public override long Length => throw new NotSupportedException();
            public override long Position
            {
                get => throw new NotSupportedException();
                set => throw new NotSupportedException();
            }
            public override void Flush() { }
            public override int Read(byte[] buffer, int offset, int count)
            {
                ObjectDisposedException.ThrowIf(disposed, this);
                int available = input.Length - inputOffset;
                if (available == 0)
                {
                    return 0;
                }
                int length = Math.Min(Math.Min(count, readChunk), available);
                Buffer.BlockCopy(input, inputOffset, buffer, offset, length);
                inputOffset += length;
                return length;
            }
            public override void Write(byte[] buffer, int offset, int count)
            {
                ObjectDisposedException.ThrowIf(disposed, this);
                written.Write(buffer, offset, count);
            }
            public override long Seek(long offset, SeekOrigin origin) =>
                throw new NotSupportedException();
            public override void SetLength(long value) =>
                throw new NotSupportedException();
            protected override void Dispose(bool disposing)
            {
                disposed = true;
                base.Dispose(disposing);
            }
        }
    }
}
