#pragma once

#if !defined(_NTDDK_) && !defined(_WDMDDK_) && !defined(_NTIFS_)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#endif

// Kernel/user contract for the experimental virtual DualSense HID source.
// DS4Windows opens \\.\HBashtonVirtualDualSense and uses these IOCTLs to
// create a VHF-backed child HID device and submit input reports to it.

#define HBASHTON_VDS_DEVICE_NAME      L"\\Device\\HBashtonVirtualDualSense"
#define HBASHTON_VDS_SYMBOLIC_LINK    L"\\DosDevices\\HBashtonVirtualDualSense"
#define HBASHTON_VDS_USER_DEVICE_PATH L"\\\\.\\HBashtonVirtualDualSense"
#define HBASHTON_VDS_CONTROL_DEVICE_NAME      L"\\Device\\HBashtonVirtualDualSenseControl"
#define HBASHTON_VDS_CONTROL_SYMBOLIC_LINK    L"\\DosDevices\\HBashtonVirtualDualSenseControl"
#define HBASHTON_VDS_USER_CONTROL_DEVICE_PATH L"\\\\.\\HBashtonVirtualDualSenseControl"

// {F7F9D9A2-16A8-49D7-AC95-75D9289A1DA6}
DEFINE_GUID(GUID_DEVINTERFACE_HBASHTON_VIRTUAL_DUALSENSE,
    0xf7f9d9a2, 0x16a8, 0x49d7, 0xac, 0x95, 0x75, 0xd9, 0x28, 0x9a, 0x1d, 0xa6);

#define HBASHTON_VDS_IOCTL_DEVICE_TYPE FILE_DEVICE_UNKNOWN

#define IOCTL_HBASHTON_VDS_CREATE_PAD CTL_CODE( \
    HBASHTON_VDS_IOCTL_DEVICE_TYPE, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HBASHTON_VDS_DESTROY_PAD CTL_CODE( \
    HBASHTON_VDS_IOCTL_DEVICE_TYPE, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HBASHTON_VDS_SUBMIT_INPUT_REPORT CTL_CODE( \
    HBASHTON_VDS_IOCTL_DEVICE_TYPE, 0x903, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HBASHTON_VDS_READ_OUTPUT_REPORT CTL_CODE( \
    HBASHTON_VDS_IOCTL_DEVICE_TYPE, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define HBASHTON_VDS_CREATE_PAD_VERSION 1

#define HBASHTON_VDS_BUS_MODE_USB 0
#define HBASHTON_VDS_BUS_MODE_BLUETOOTH 1

typedef struct _HBASHTON_VDS_CREATE_PAD_IN
{
    ULONG Size;
    ULONG Version;
    ULONG BusMode;
    ULONG Flags;
} HBASHTON_VDS_CREATE_PAD_IN, *PHBASHTON_VDS_CREATE_PAD_IN;

typedef struct _HBASHTON_VDS_CREATE_PAD_OUT
{
    ULONG PadId;
} HBASHTON_VDS_CREATE_PAD_OUT, *PHBASHTON_VDS_CREATE_PAD_OUT;

typedef struct _HBASHTON_VDS_PAD_REQUEST
{
    ULONG PadId;
} HBASHTON_VDS_PAD_REQUEST, *PHBASHTON_VDS_PAD_REQUEST;

#define HBASHTON_DUALSENSE_USB_INPUT_REPORT_ID 0x01
#define HBASHTON_DUALSENSE_USB_INPUT_REPORT_SIZE 64
#define HBASHTON_DUALSENSE_BLUETOOTH_INPUT_REPORT_ID 0x01
#define HBASHTON_DUALSENSE_BLUETOOTH_INPUT_REPORT_SIZE 10
#define HBASHTON_DUALSENSE_MAX_OUTPUT_REPORT_SIZE 1024

typedef struct _HBASHTON_VDS_SUBMIT_INPUT_REPORT_IN
{
    ULONG PadId;
    UCHAR Report[1];
} HBASHTON_VDS_SUBMIT_INPUT_REPORT_IN, *PHBASHTON_VDS_SUBMIT_INPUT_REPORT_IN;

#define HBASHTON_VDS_SUBMIT_INPUT_REPORT_MIN_SIZE \
    (FIELD_OFFSET(HBASHTON_VDS_SUBMIT_INPUT_REPORT_IN, Report) + 1)

typedef struct _HBASHTON_VDS_READ_OUTPUT_REPORT_OUT
{
    ULONG PadId;
    ULONG Sequence;
    ULONG ReportLength;
    UCHAR Report[HBASHTON_DUALSENSE_MAX_OUTPUT_REPORT_SIZE];
} HBASHTON_VDS_READ_OUTPUT_REPORT_OUT, *PHBASHTON_VDS_READ_OUTPUT_REPORT_OUT;
